spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    servlet.corsEnabled: true
    schema.printer.enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/movies?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 127.0.0.1:29092

auto:
  create:
    topic:
      enable: true

app:
  cors:
    allowed-origins: http://localhost:3000